# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  required_plugins = %w( vagrant-hostmanager )
  _retry = false

  required_plugins.each do |plugin|
    unless Vagrant.has_plugin? plugin
      system "vagrant plugin install #{plugin}"
      _retry=true
    end
  end

  if (_retry)
    exec "vagrant " + ARGV.join(' ')
  end

  config.vm.box = 'ubuntu/trusty64'

  config.vm.network "private_network", type: "dhcp"
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = false
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "mysql" do |mysql|
    mysql.vm.hostname = "mysql.local"
    mysql.vm.provider "virtualbox" do |vb|
      vb.memory = 512
    end
    mysql.vm.provision "ansible" do |ansible|
      ansible.playbook = "./ansible/playbook.yml"
      ansible.verbose = "v"
      ansible.sudo = true
    end

    config.vm.define "backup" do |backup|
      backup.vm.hostname = "backup.local"
      backup.vm.provider "virtualbox" do |vb|
        vb.memory = 512
      end
    end
  end
end
